# Generated by Django 4.0.6 on 2022-07-21 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correction', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Text',
            new_name='OcrExtractedText',
        ),
    ]
