# Generated by Django 4.0.6 on 2022-07-22 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correction', '0002_rename_text_ocrextractedtext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocrextractedtext',
            name='pub_date',
        ),
    ]
